services:
  memory-service:
    image: python:3.10-slim
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ${SQLITE_DB_PATH:-$HOME/mcp-memory/sqlite_db}:/app/sqlite_db
      - ${BACKUPS_PATH:-$HOME/mcp-memory/backups}:/app/backups
    environment:
      - MCP_MEMORY_STORAGE_BACKEND=sqlite_vec
      - MCP_MEMORY_SQLITE_PATH=/app/sqlite_db
      - MCP_MEMORY_BACKUPS_PATH=/app/backups
      - LOG_LEVEL=INFO
      - MAX_RESULTS_PER_QUERY=10
      - SIMILARITY_THRESHOLD=0.7
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - CHROMA_TELEMETRY_IMPL=none
      - ANONYMIZED_TELEMETRY=false
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile